<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:theme="@style/Theme.NeuroLog"
        android:supportsRtl="true">

        <activity
            android:name="com.example.neurolog.MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name="com.example.neurolog.GameActivity"
            android:exported="false"
            android:label="اختبار ستروب" />

    </application>

</manifest>
